# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test_flutter: 
    name: run flutter and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: flutter format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: flutter test

  # build_ios: 
  #   name: build flutter for ios
  #   needs: [test_flutter]
  #   runs-on: macos-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         channel: "stable"

  #     - name: Install dependencies
  #       run: flutter pub get

  #     - name: Clean for rebuild
  #       run: flutter clean

  #     - name: Build for ios
  #       run: flutter build ios --release --no-codesign

  # build_android: 
  #   name: build flutter for android
  #   needs: [test_flutter]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         channel: "stable"

  #     - name: Install dependencies
  #       run: flutter pub get

  #     - name: Clean for rebuild
  #       run: flutter clean

  #     - name: Build for android
  #       run: flutter build apk